<?php include '../analytics.php' ?>
<?php
$tenisArray = array(
	/* ANO abre */
	array(
		'ano' => '2006',
		'modelos' => array(
			array(
				'exibir' => true,
				'id' => 1,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => 'O primeiro Riva foi lançado em duas versões, ambas de couro. Uma curiosidade é que as primeiras edições do tênis possuem um dos passadores em preto, um detalhe que não foi repetido.',
				'link_compra' => 'http://store.osklen.com/catalogsearch/result/?q=11697',
				'link_compart' => 'http://store.osklen.com/tenis-riva-81502.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697',
				'fotos' => array('00_Riva_Classico_Masc1', '00_Riva_Classico_Masc2'),
			),
		),
	),
	/* ANO fecha */
	/* ANO abre */
	array(
		'ano' => '2007',
		'modelos' => array(
			array(
				'exibir' => true,
				'id' => 1,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => 'O primeiro Riva feminino foi desenvolvido em napa de couro e ganhou tonalidades suaves, seguindo as cores da coleção Neotropical.',
				'link_compra' => 'http://store.osklen.com/catalogsearch/result/?q=11697',
				'link_compart' => 'http://store.osklen.com/tenis-riva-81502.html',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '12606',
				'fotos' => array('00_Riva_ClassicoFem1','00_Riva_Classico_Masc1'),
			),
		),
	),
	/* ANO fecha */
	/* ANO abre  */
	array(
		'ano' => '2008',
		'modelos' => array(
			array(
				'exibir' => true,
				'id' => 1,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => 'Continuando o sucesso de lançamento, o Riva ganha, pela primeira vez, versão unissex, desenvolvido em tamanhos para os públicos feminino e masculino.',
				'link_compra' => 'http://store.osklen.com/catalogsearch/result/?q=11697',
				'link_compart' => 'http://store.osklen.com/tenis-riva-81502.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697',
				'fotos' => array('00_Riva_Classico_Masc1'),
			),
		),
	),
	/* ANO fecha */
	/* ANO abre */
	array(
		'ano' => '2009',
		'modelos' => array(
			array(
				'exibir' => true,
				'id' => 1,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => 'O Riva tem seus detalhes suavizados, ressaltando a característica sofisticada da peça. O primeiro modelo de couro texturizado lançado é relançado agora também para as mulheres.',
				'link_compra' => 'http://store.osklen.com/catalogsearch/result/?q=11697',
				'link_compart' => 'http://store.osklen.com/tenis-riva-81502.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697/12606',
				'fotos' => array('00_Riva_Classico_Masc1','00_Riva_Classico_Masc2','00_Riva_Classico_Masc3','00_Riva_ClassicoFem2'),
			),
		),
	),
	/* ANO fecha */
	/* ANO abre */
	array(
		'ano' => '2010',
		'modelos' => array(
			array(
				'exibir' => true,
				'id' => 1,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => 'O cinza tem suas nuances combinadas a diferentes tons, além dos detalhes metalizados.',
				'link_compra' => 'http://store.osklen.com/catalogsearch/result/?q=11697',
				'link_compart' => 'http://store.osklen.com/tenis-riva-81502.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697/12606',
				'fotos' => array('00_Riva_ClassicoFem1','00_Riva_Classico_Masc3','00_Riva_Classico_Masc1','00_Riva_Classico_Masc2','00_Riva_Classico_Masc4','00_Riva_Classico_Masc5','00_Riva_ClassicoFem2'),
			),
			array(
				'exibir' => true,
				'id' => 2,
				'nome' => 'RIVA <span>NEW GOLD</span>',
				'descricao' => 'Primeiro Riva de couro metalizado com efeito craquelado. O modelo tem aparência desgastada, trazendo textura para o tênis. Essa se tornou uma das edições mais conhecidas e relançada em novas coleções.',
				'link_compra' => 'http://store.osklen.com/tenis-riva-new-gold-fem.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-new-gold-fem.html',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '23822',
				'fotos' => array('01_Riva_NewGold'),
			),
			array(
				'exibir' => true,
				'id' => 3,
				'nome' => 'RIVA <span>BIG FLOATER</span>',
				'descricao' => 'Continuando o trabalho com o couro, o Riva feminino aparece monocromático, exceto pelo detalhe em tom caramelo. A técnica utlizada criou texturas que formam pequenos relevos em todo o calçado.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => false,
				'tipo' => 'F',
				'ref' => '23350',
				'fotos' => array('02_Riva_BigFloater'),
			),
			array(
				'exibir' => true,
				'id' => 4,
				'nome' => 'RIVA <span>LÃ COLLECTION</span>',
				'descricao' => 'Elementos sofisticados e esportivos se misturam na criação do primeiro Riva Collection, linha premium da Osklen. O tênis desenvolvido em lã leva para os pés a trama clássica do inverno. O trabalho com tecidos passou a ser explorado constantemente pela Osklen.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => false,
				'tipo' => 'M',
				'ref' => '24882',
				'fotos' => array('04_Riva_La'),
			),
		),
	),
	/* ANO fecha */
	/* ANO abre */
	array(
		'ano' => '2011',
		'modelos' => array(
		
			array(
				'exibir' => true,
				'id' => 2,
				'nome' => 'RIVA <span>FENIX</span>',
				'descricao' => 'O Riva Fenix simboliza o efeito do incêndio no acervo Osklen. O modelo foi desenvolvido em tecido soft drill, com efeito estonado. O solado foi trabalhado manualmente para acentuar o aspecto chamuscado. Pela primeira vez, a palmilha traz o carimbo da coleção.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => false,
				'tipo' => 'M',
				'ref' => '29858',
				'fotos' => array('01_Riva_Fenix'),
			),
	
		
			array(
				'exibir' => true,
				'id' => 3,
				'nome' => 'RIVA <span>MOLETOM</span>',
				'descricao' => 'Após a lã, o moletom é experimentado no Riva e reveste todo o modelo do tênis unissex.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => false,
				'tipo' => 'F',
				'ref' => '29789',
				'fotos' => array('02_Riva_Moletom'),
			),
			array(
				'exibir' => true,
				'id' => 4,
				'nome' => 'RIVA <span>ENLUVADO</span>',
				'descricao' => 'Versão clean do clássico, com as costuras ocultadas. A edição foi desenvolvida em couro monocromático, ressaltando sua sofisticação.',
				'link_compra' => 'http://store.osklen.com/tenis-riva-enluvado-masc-49851.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-enluvado-masc-49851.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '29798',
				'fotos' => array('03_Riva_Enluvado1','03_Riva_Enluvado2','03_Riva_Enluvado3','03_Riva_Enluvado4','03_Riva_Enluvado5','03_Riva_Enluvado6'),
			),
			array(
				'exibir' => true,
				'id' => 5,
				'nome' => 'RIVA <span>CETIM</span>',
				'descricao' => 'Como os demais tecidos, o cetim é normalmente associado à roupas. Aqui ele aparece revestindo o Riva. O modelo tem ponteiras de metal dourado aplicadas nos cadarços.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => false,
				'tipo' => 'F',
				'ref' => '29799',
				'fotos' => array('04_Riva_Cetim2','04_Riva_Cetim1'),
			),
			array(
				'exibir' => true,
				'id' => 6,
				'nome' => 'RIVA <span>TIGRE</span>',
				'descricao' => 'A Osklen quebra mais um mito ao apresentar o Riva Animal Print produzido para homens e mulheres. O modelo tem estampa tigrada aplicada no couro com textura de pelos.',
				'link_compra' => 'http://store.osklen.com/catalog/product/view/id/12954',
				'link_compart' => 'http://store.osklen.com/catalog/product/view/id/12954',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '30145',
				'fotos' => array('05_Riva_Tigre'),
			),
			array(
				'exibir' => true,
				'id' => 7,
				'nome' => 'RIVA <span>ESPELHO</span>',
				'descricao' => 'O modelo Collection foi produzido em couro espelhado, efeito criado através da aplicação de filme metalizado no couro, combinando com os variados tons de azul trabalhados em toda a coleção.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => false,
				'tipo' => 'F',
				'ref' => '27584',
				'fotos' => array('06_Riva_Espelho'),
			),
			array(
				'exibir' => true,
				'id' => 8,
				'nome' => 'RIVA <span>COURO DE PEIXE</span>',
				'descricao' => 'Após aparecer no tênis Arpoador e outros acessórios, o couro de salmão é utilizado pela primeira vez no Riva. O material é resultado da pesquisa realizada junto ao Instituto-e, dentro do projeto e-fabrics (saiba mais em e-fabrics.com.br), que busca soluções ecológicas para diminuir o impacto ambiental causado pela indústria têxtil.',
				'link_compra' => 'http://store.osklen.com/catalog/product/view/id/20428',
				'link_compart' => 'http://store.osklen.com/catalog/product/view/id/20428',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '27599',
				'fotos' => array('07_Riva_LonaCouroPeixe'),
			),
			array(
				'exibir' => true,
				'id' => 9,
				'nome' => 'RIVA <span>LONA BICOLOR</span>',
				'descricao' => 'O clássico preto e branco foi levado para o Riva que, pela primeira vez, aparece com o solado personalizado em preto.',
				'link_compra' => 'http://store.osklen.com/tenis-riva-lona-bicolor-48201.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-lona-bicolor-48201.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '27615',
				'fotos' => array('08_Riva_LonaBicolor2','08_Riva_LonaBicolor3'),
			),
			array(
				'exibir' => true,
				'id' => 10,
				'nome' => 'RIVA <span>LONA LISA</span>',
				'descricao' => 'O trabalho colour, já utilizado nas roupas da Osklen, é aplicado na lona de algodão, que ganha tons vibrantes. Foram criadas edições feminina e masculina e o modelo faz parte até hoje das coleções da marca.',
				'link_compra' => 'http://store.osklen.com/tenis-riva-lona-lisa-masc-52920.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-lona-lisa-masc-52920.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '28060',
				'fotos' => array('08_Riva_LonaLisa3','08_Riva_LonaLisa2','08_Riva_LonaLisa4','08_Riva_LonaLisa5'),
			),
			
					array(
				'exibir' => true,
				'id' => 1,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => 'As edições lançadas esse ano trazem combinações inéditas, inspiradas no efeito do fogo sobre tecidos, por exemplo o cinza com prata, além dos detalhes em couro metalizado, como aparece no Riva chumbo com cinza.',
				'link_compra' => 'http://store.osklen.com/catalogsearch/result/?q=11697',
				'link_compart' => 'http://store.osklen.com/tenis-riva-81502.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697/12606',
				'fotos' => array('00_Riva_Classico_Masc3','00_Riva_Classico_Masc1','00_Riva_Classico_Masc2','00_Riva_Classico_Masc4','00_Riva_ClassicoFem1'),
			),
		),
	),
	/* ANO fecha */
	/* ANO abre */
	array(
		'ano' => '2012',
		'modelos' => array(
		
		
			array(
				'exibir' => true,
				'id' => 3,
				'nome' => 'RIVA <span>LONA ECO</span>',
				'descricao' => 'Royal Black é marcada pela mistura dos tons cru, caramelo e preto, além de texturas naturais. Inspirado na coleção, esse Riva foi desenvolvido em lona e-fabrics com detalhes de couro.',
				'link_compra' => 'http://store.osklen.com/catalog/product/view/id/25748',
				'link_compart' => 'http://store.osklen.com/catalog/product/view/id/25748',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '31425',
				'fotos' => array('02_Riva_Eco_eCouro'),
			),
			
			array(
				'exibir' => true,
				'id' => 2,
				'nome' => 'RIVA <span>ONÇA</span>',
				'descricao' => 'Após o sucesso do Riva Tigre, a Osklen lança um novo animal print texturizado, dessa vez com estampa onça, em tamanhos masculino e feminino.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => false,
				'tipo' => 'F',
				'ref' => '27256',
				'fotos' => array('01_Riva_Oncinha_1','01_Riva_Oncinha_2'),
			),
		
			array(
				'exibir' => true,
				'id' => 4,
				'nome' => 'RIVA <span>LONA METALIZADA</span>',
				'descricao' => 'Característico da coleção Royal Black, o dourado e a prata simbolizam a riqueza e sofisticação da cultura negra. Após o trabalho metalizado no couro, dessa vez a lona de algodão ganha o efeito, ressaltando a elegância que existe também em materiais básicos.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => false,
				'tipo' => 'F',
				'ref' => '31746',
				'fotos' => array('03_Riva_Lona_Metalizada1','03_Riva_Lona_Metalizada2'),
			),
			array(
				'exibir' => true,
				'id' => 5,
				'nome' => 'RIVA <span>COURO PIQUET</span>',
				'descricao' => 'Desenvolvido em napa de couro, o Riva Couro Piquet é caracterizado pelos micro-furos feitos com aplicação de prensa de metal quente na superfície do couro. Essa foi a primeira vez que a técnica foi aplicada no tênis.',
				'link_compra' => 'http://store.osklen.com/tenis-riva-couro-piquet-masc-48149.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-couro-piquet-masc-48149.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '32192',
				'fotos' => array('04_Riva_Couro_Piquet1','04_Riva_Couro_Piquet2','04_Riva_Couro_Piquet3'),
			),
			array(
				'exibir' => true,
				'id' => 6,
				'nome' => 'RIVA <span>ENLUVADO</span>',
				'descricao' => 'Reedição do modelo clean do Riva, com as costuras embutidas. A partir desse ano também começam a ser trabalhados os cadarços de algodão encerado nas mesmas cores.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => false,
				'tipo' => 'M',
				'ref' => '32194',
				'fotos' => array('05_Riva_Enluvado'),
			),
			array(
				'exibir' => true,
				'id' => 7,
				'nome' => 'RIVA <span>VELVET</span>',
				'descricao' => 'Tênis Riva Collection desenvolvido em veludo. O modelo é essencialmente feminino, com ponteiras de metal dourado aplicadas nos cadarços.',
				'link_compra' => 'http://store.osklen.com/tenis-riva-velvet-fem.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-velvet-fem.html',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '32567',
				'fotos' => array('06_Riva_Velvet1','06_Riva_Velvet2'),
			),
			array(
				'exibir' => true,
				'id' => 8,
				'nome' => 'RIVA <span>PSICODÉLICO</span>',
				'descricao' => 'Principal estampa da coleção A21, o Riva Psicodélico aparece em lona de algodão. O modelo possui versões masculina e feminina e é caracterizado pelas cores marcantes.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => false,
				'tipo' => 'F',
				'ref' => '33574',
				'fotos' => array('07_Riva_Psicodelico'),
			),
			array(
				'exibir' => true,
				'id' => 9,
				'nome' => 'RIVA <span>CETIM ENLUVADO</span>',
				'descricao' => 'Nova versão do Riva Cetim, dessa vez com detalhes em couro e costuras não aparentes. O modelo foi desenvolvido em tamanho feminino.',
				'link_compra' => 'http://store.osklen.com/tenis-riva-cetim-enluvado-fem-55939.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-cetim-enluvado-fem-55939.html',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '33529',
				'fotos' => array('08_Riva_Cetim_Enluvado1','08_Riva_Cetim_Enluvado2','08_Riva_Cetim_Enluvado3','08_Riva_Cetim_Enluvado4'),
			),
			array(
				'exibir' => true,
				'id' => 10,
				'nome' => 'RIVA <span>ROUGH</span>',
				'descricao' => 'O modelo monocromático mantém os traços manchados naturais do couro, resultado do trabalho artesanal feito no tênis. A técnica faz com que um par nunca seja igual ao outro. O modelo é um dos mais conhecidos e desejados e é reeditado a cada temporada.',
				'link_compra' => 'http://store.osklen.com/tenis-riva-rough-masc.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-rough-masc.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '33568',
				'fotos' => array('09_Riva_Rough'),
			),
			
			array(
				'exibir' => true,
				'id' => 1,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => 'Mais sofisticado, em 2012 o Riva Clássico ganha contrastes suaves e elegantes,  dentro das inspirações vindas das coleções Royal Black e A21.',
				'link_compra' => 'http://store.osklen.com/catalogsearch/result/?q=11697',
				'link_compart' => 'http://store.osklen.com/tenis-riva-81502.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697/12606',
				'fotos' => array('00_Riva_Classico_Masc1','00_Riva_Classico_Masc2','00_Riva_Classico_Masc3','00_Riva_Classico_Masc4','00_Riva_Classico_Masc5','00_Riva_Classico_Masc6','00_Riva_ClassicoFem1','00_Riva_ClassicoFem2','00_Riva_ClassicoFem3'),
			),
			
		),
	),
	/* ANO fecha */
	/* ANO abre */
	array(
		'ano' => '2013',
		'modelos' => array(
			array(
				'exibir' => true,
				'id' => 1,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => 'A sofisticação e o esporte se reunem nesse clássico lançado em 2013, incluindo contrastes suaves, como o verde, cinza e azul, e o preto, laranja e caramelo. O trabalho colour, aplicado até então somente na lona de algodão, aparece agora no couro.',
				'link_compra' => 'http://store.osklen.com/catalogsearch/result/?q=11697',
				'link_compart' => 'http://store.osklen.com/tenis-riva-81502.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697/12606',
				'fotos' => array('00_Riva_Classico_Masc1','00_Riva_Classico_Masc2','00_Riva_Classico_Masc3','00_Riva_Classico_Masc5','00_Riva_ClassicoFem1','00_Riva_ClassicoFem2','00_Riva_ClassicoFem3','00_Riva_ClassicoFem4'),
			),
			array(
				'exibir' => true,
				'id' => 2,
				'nome' => 'RIVA <span>PELO</span>',
				'descricao' => 'Na coleção Into the Mountains, o couro com textura de pelo aparece vazado, com microfuros, em uma referência ao Riva Couro Piquet.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => false,
				'tipo' => 'M',
				'ref' => '38014',
				'fotos' => array('01_Riva_Microfuros'),
			),
			array(
				'exibir' => true,
				'id' => 3,
				'nome' => 'RIVA <span>SPORT</span>',
				'descricao' => 'Inspirado nos materiais dos clássicos tênis de performance, o Riva Sport mistura o nylon esportivo e a camurça de couro.',
				'link_compra' => 'http://store.osklen.com/tenis-riva-sport-masc-34012.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-sport-masc-34012.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '38132',
				'fotos' => array('02_Riva_Sport_1','02_Riva_Sport_2','02_Riva_Sport_3','02_Riva_Sport_4'),
			),
			array(
				'exibir' => true,
				'id' => 4,
				'nome' => 'RIVA <span>CAMURÇA GRAXO</span>',
				'descricao' => 'Esse modelo ganha efeito graxo a partir do trabalho manual aplicado nele após pronto. A técnica foi concentrada principalmente no bico e calcanhar e, por ser manual, torna cada par único.',
				'link_compra' => 'http://store.osklen.com/tenis-riva-camurca-graxo-masc.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-camurca-graxo-masc.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '38167',
				'fotos' => array('03_Riva_CamurcaGraxo_1','03_Riva_CamurcaGraxo_2','03_Riva_CamurcaGraxo_3'),
			),
			array(
				'exibir' => true,
				'id' => 5,
				'nome' => 'RIVA <span>NERVURAS</span>',
				'descricao' => 'Desde a coleção Rio de Janeiro, as nervuras transitam pelas roupas da Osklen e já são uma característica própria da marca. No Riva desenvolvido em napa de couro, a faixa lateral é renovada e substituida pela técnica dando nova cara ao detalhe clássico do modelo.',
				'link_compra' => 'http://store.osklen.com/tenis-arpoador-soft-wrinkled-masc-51929.html',
				'link_compart' => 'http://store.osklen.com/tenis-arpoador-soft-wrinkled-masc-51929.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '35632',
				'fotos' => array('04_Riva_Nervuras'),
			),
			array(
				'exibir' => true,
				'id' => 6,
				'nome' => 'RIVA <span>A TOPO</span>',
				'descricao' => 'Na coleção Endless Summer, o Riva é colocado ao avesso. O modelo Riva a Topo foi desenvolvido em camurça de couro, parte da linha Collection, com a costura virada para fora, marcando seus recortes. O tênis é caracterizado também por não possuir o clássico trio frontal de ilhoses.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => false,
				'tipo' => 'M',
				'ref' => '33572',
				'fotos' => array('05_Riva_A_Topo'),
			),
			array(
				'exibir' => true,
				'id' => 7,
				'nome' => 'RIVA <span>BOLD</span>',
				'descricao' => 'Inspirado no coturno dos uniformes militares brasileiro, o Riva Bold apresenta um couro mais robusto.',
				'link_compra' => 'http://store.osklen.com/tenis-riva-bold-masc.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-bold-masc.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '33850',
				'fotos' => array('07_Riva_Bold'),
			),
			array(
				'exibir' => true,
				'id' => 8,
				'nome' => 'RIVA <span>LINHO</span>',
				'descricao' => 'O visual da praia e sua vestimenta característica inspira o Riva Linho, produzido pela primeira vez na trama natural. O modelo feminino e masculino tem a costura embutida a fim de deixar o visual ainda mais limpo.',
				'link_compra' => 'http://store.osklen.com/tenis-riva-linho.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-linho.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '35585',
				'fotos' => array('08_Riva_Linho'),
			),
		),
	),
	/* ANO fecha */
	/* ANO abre */
	array(
		'ano' => '2014',
		'modelos' => array(
		
			array(
				'exibir' => true,
				'id' => 8,
				'nome' => 'RIVA <span>FOOTBALL SERIES</span>',
				'descricao' => 'Riva Special Edition desenvolvido em lona de algodão para a coleção Football Series. Diferente dos demais modelos, esse ganha solado verde e faixa dupla personalizada em amarelo e branco, além de ter carimbo da coleção aplicado na palmilha.',
				'link_compra' => 'http://store.osklen.com/tenis-riva-futebol-series-fem.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-futebol-series-fem.html',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '43641',
				'fotos' => array('08_Riva_FootballSeries_fem'),
			),
			
			array(
				'exibir' => true,
				'id' => 1,
				'nome' => 'RIVA <span>COURO</span> COLOUR',
				'descricao' => 'O Riva Clássico ganha novas edições colour, com tons ainda mais vibrantes. As cores vivas são sofisticadas pela combinação com tons neutros, como o branco e o preto. Em outro momento, é lançado também edição especial, nas cores verde, amarelo e branco, dentro da coleção Football Series.',
				'link_compra' => 'http://store.osklen.com/tenis-riva-couro-colour-fem-52876.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-couro-colour-fem-52876.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '42136',
				'fotos' => array('05_Riva_courocolor_fem2','00_Riva_Classico_masc1','00_Riva_Classico_masc2','00_Riva_Classico_masc4','05_Riva_courocolor_fem1'),
			),
			array(
				'exibir' => true,
				'id' => 2,
				'nome' => 'RIVA <span>BLURRY GRANDSTAND</span>',
				'descricao' => 'Estampa desenvolvida a partir de fotografia da torcida durante uma partida de futebol no estádio Maracanã. A imagem foi trabalhada digitalmente para alcançar o efeito blured que você vê no resultado final do tênis.',
				'link_compra' => 'http://store.osklen.com/catalog/product/view/id/48958',
				'link_compart' => 'http://store.osklen.com/catalog/product/view/id/48958',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '42146',
				'fotos' => array('01_Riva_Grandstand_fem'),
			),
			array(
				'exibir' => true,
				'id' => 3,
				'nome' => 'RIVA <span>MATELASSÊ</span>',
				'descricao' => 'Desenvolvido em napa de couro, o Riva Matelassê se inspira nos uniformes dos goleiros e bolas de futebol antigas e ganha o efeito característico nos recortes do tênis. O material trabalhado é leve e macio a fim de tornar o matelassê mais evidente.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => false,
				'tipo' => 'F',
				'ref' => '41249',
				'fotos' => array('02_Riva_Matelasse'),
			),
			array(
				'exibir' => true,
				'id' => 4,
				'nome' => 'RIVA <span>MESCLA</span>',
				'descricao' => 'A malha mescla é conhecida por ser trabalhada em roupas para joggings e outros treinos. Ela surge pela primeira vez no Riva.',
				'link_compra' => 'http://store.osklen.com/catalog/product/view/id/47837',
				'link_compart' => 'http://store.osklen.com/catalog/product/view/id/47837',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '41251',
				'fotos' => array('04_Riva_Mescla'),
			),
				
	
			array(
				'exibir' => true,
				'id' => 7,
				'nome' => 'RIVA <span>SALMÃO COLLECTION</span>',
				'descricao' => 'Após aparecer somente em detalhes, pela primeira vez o Riva é desenvolvido 100% em couro de salmão, parte do projeto e-fabrics.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => false,
				'tipo' => 'M',
				'ref' => '42149',
				'fotos' => array('07_Riva_Salmao'),
			),
		
			array(
				'exibir' => true,
				'id' => 9,
				'nome' => 'RIVA <span>TROPICAL STONES</span>',
				'descricao' => 'O Riva Tropical Stones é desenvolvido em lona de algodão e ganha estampa emblemática da coleção 5521RIO, inspirada em gemas preciosas e marcada por suas cores vibrantes e formas geométricas.',
				'link_compra' => 'http://store.osklen.com/catalog/product/view/id/40946',
				'link_compart' => 'http://store.osklen.com/catalog/product/view/id/40946',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '39633',
				'fotos' => array('09_Riva_TropicalStones'),
			),
			array(
				'exibir' => true,
				'id' => 10,
				'nome' => 'RIVA <span>VINTAGE</span>',
				'descricao' => 'A inspiração para o Riva Vintage vem dos antigos tênis utilizados por skatistas, depois de já desgastados. Para alcançar o efeito, o modelo de couro recebe trabalho manual em cada par.',
				'link_compra' => 'http://store.osklen.com/tenis-riva-vintage-masc.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-vintage-masc.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '39645',
				'fotos' => array('10_Riva_Vintage'),
			),
		),
	),
	/* ANO fecha */
	/* ANO abre */
	array(
		'ano' => '2015',
		'modelos' => array(
		
		array(
				'exibir' => true,
				'id' => 1,
				'nome' => 'RIVA <span>RED VENUS</span> BLACK',
				'descricao' => 'A estampa Red Venus Black foi desenvolvida em Inhotim durante imersão criativa. A imagem foi criada originalmente para a intervenção artística "Interfaces" de Oskar Metsavaht, apresentada ao público em setembro de 2014, na exposição "Feito por Brasileiros". A exposição ocupou as salas do antigo Hospital Matarazzo, em São Paulo.',
				'link_compra' => 'http://store.osklen.com/tenis-riva-couro-colour-fem-52876.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-couro-colour-fem-52876.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '44488',
				'fotos' => array('00_Riva_RedVenusK_fem'),
			),
			
			array(
				'exibir' => true,
				'id' => 5,
				'nome' => 'RIVA <span>COURO LIXADO</span>',
				'descricao' => 'Nessa edição, o couro é lixado manualmente após o tênis estar pronto, criando efeito único e explorando novas texturas. Em edição especial, o modelo foi desenvolvimento do tamanho 33 ao 46.',
				'link_compra' => 'http://store.osklen.com/catalog/product/view/id/47837',
				'link_compart' => 'http://store.osklen.com/catalog/product/view/id/47837',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '44242',
				'fotos' => array('04_Riva_Couro_Lixado'),
			),
			array(
				'exibir' => true,
				'id' => 3,
				'nome' => 'RIVA <span>LONA RACLADA</span>',
				'descricao' => 'A lona de algodão ganha lavagem especial para atenuar o efeito do tingimento, tendo como resultado cores suaves e únicas. Em edição especial, o Riva Lona Raclada foi desenvolvido do tamanho 35 ao 46.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '44259',
				'fotos' => array('02_Riva_LonaRac2','02_Riva_LonaRac1','02_Riva_LonaRac3','02_Riva_LonaRac4'),
			),
			array(
				'exibir' => true,
				'id' => 4,
				'nome' => 'RIVA <span>ENLUVADO PIQUET</span>',
				'descricao' => 'Reeditado, o Riva Piquet aparece com a costura embutida. O modelo monocromático é feito de napa de couro e se torna ainda mais sofisticado com os micro-furos característicos da técnica piquet. Em edição especial, esse Riva foi desenvolvido do tamanho 33 ao 46.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '43702',
				'fotos' => array('03_Riva_Enluvado1','03_Riva_Enluvado2'),
			),
			
		
			array(
				'exibir' => true,
				'id' => 6,
				'nome' => 'RIVA <span>COURO</span> COLOUR',
				'descricao' => 'Antes com detalhes em camurça ou desgastado, nessa coleção o Riva Couro Colour é trabalhado totalmente liso, deixando a atenção para suas tonalidades vibrantes. Em edição especial, o modelo foi desenvolvimento do tamanho 33 ao 41.',
				'link_compra' => 'http://store.osklen.com/tenis-riva-futebol-series-fem.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-futebol-series-fem.html',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '11697',
				'fotos' => array('05_Riva_CouroColour1','05_Riva_CouroColour2','05_Riva_CouroColour3'),
			),
			
			
			array(
				'exibir' => true,
				'id' => 2,
				'nome' => 'RIVA <span>COURO STONED</span>',
				'descricao' => 'O couro ganha trabalho stoned, que cria efeito desgastado em todo o modelo. A técnica cria variações de tonalidade e textura que são características e não configuram defeito. Em edição especial, o modelo foi desenvolvimento do tamanho 33 ao 46.',
				'link_compra' => 'http://store.osklen.com/tenis-riva-couro-stoned-masc.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-couro-stoned-masc.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '44243',
				'fotos' => array('01_Riva_CouroStoned'),
			),
			
			
				
	
			
		),
	),
	/* ANO fecha */
			
);
?>