<?php
$tenisArray = array(
	/* ANO abre */
	array(
		'ano' => '2006',
		'modelos' => array(
			array(
				'exibir' => true,
				'id' => 1,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => 'Primeiro modelo do Riva. Desenhado em 2005 e lançado no inverno de 2006, o tênis foi pensado, a princípio, para o público masculino. Desenvolvido em três cores, o Riva tem como diferencial clássico o taco lateral e cabedal em tons diferentes do restante do modelo. A peça foi produzida em couro, incluindo forro e palmilha e solado personalizado que, juntos, caracterizam o tênis.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697-03',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 2,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697-10',
				'fotos' => array(1),
			),
		),
	),
	/* ANO fecha */
	/* ANO abre */
	array(
		'ano' => '2007',
		'modelos' => array(),
	),
	/* ANO fecha */
	/* ANO abre */
	array(
		'ano' => '2008',
		'modelos' => array(),
	),
	/* ANO fecha */
	/* ANO abre */
	array(
		'ano' => '2009',
		'modelos' => array(
			array(
				'exibir' => true,
				'id' => 1,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697-0324',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 2,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697-5959',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 3,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697-1873',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 4,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '12606-10',
				'fotos' => array(1),
			),
		),
	),
	/* ANO fecha */
	/* ANO abre */
	array(
		'ano' => '2010',
		'modelos' => array(
			array(
				'exibir' => true,
				'id' => 1,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697-0530',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 2,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697-0407',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 3,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697-05',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 4,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697-0424',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 5,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697-0427',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 6,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '12606-0421',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 7,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '12606-0407',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 8,
				'nome' => 'RIVA NEW GOLD',
				'descricao' => 'O couro metalizado ganha efeito craquelado, com aparência desgastada, nessa edição do Riva desenvolvida em versões masculina e feminina. O modelo é um dos mais conhecidos e aparece a cada temporada.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '23822',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 9,
				'nome' => 'RIVA BIG FLOATER',
				'descricao' => 'Continuando o trabalho com o couro, o Riva feminino aparece monocromático, exceto pelo cabedal em tom caramelo,  e com texturas que formam pequenos relevos.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '23350',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 10,
				'nome' => 'RIVA LÃ',
				'descricao' => 'Continuando o trabalho com o couro, o Riva feminino aparece monocromático, exceto pelo cabedal em tom caramelo,  e com texturas que formam pequenos relevos.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '24882',
				'fotos' => array(1),
			),
			array(
				'exibir' => false,
				'id' => 11,
				'nome' => 'RIVA OXFORD',
				'descricao' => 'O clássico sapato irlandês inspira o Riva Oxford masculino, desenvolvido em couro, e mantendo ainda as características originais do tênis da Osklen.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '22131',
				'fotos' => array(1),
			),
			array(
				'exibir' => false,
				'id' => 12,
				'nome' => 'RIVA LONA',
				'descricao' => 'Primeiro Riva desenvolvido em lona stone, um material clássico que aparece em inúmeros produtos Osklen e tem como principal característica seu aspecto overused. Versões feminina e masculina.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '24429',
				'fotos' => array(1),
			),
			array(
				'exibir' => false,
				'id' => 13,
				'nome' => 'RIVA NOBUCK',
				'descricao' => 'A coleção Trópico de Capricórnio foi marcada também pelo primeiro Riva produzido em nobuck que, nas temporadas seguintes, ganhou novas cores, mantendo seu aspecto bold e se tornando um dos preferidos. Versões masculina e feminina.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '2551975',
				'fotos' => array(1),
			),
			array(
				'exibir' => false,
				'id' => 14,
				'nome' => 'RIVA SUEDE GLITTER',
				'descricao' => 'Seguindo o tema da coleção, o Riva feminino foi produzido pela primeira vez em camurça suede com glitter. A peça ganha aplicação metalizada no avesso do couro, criando aspecto overused, similar à lona stone.',
				'link_compra' => '',
				'link_compart' => '',
				'tipo' => 'F',
				'ref' => '25525',
				'disponivel' => true,
				'fotos' => array(1),
			),
		),
	),
	/* ANO fecha */
	/* ANO abre */
	array(
		'ano' => '2011',
		'modelos' => array(
			array(
				'exibir' => true,
				'id' => 1,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697-1733',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 2,
				'nome' => 'RIVA FENIX',
				'descricao' => 'A coleção tem como inspiração o incêndio sofrido pela sede da Osklen aquele ano. Das chamas e  objetos remanescentes surgiram estampas e ideias de materiais trabalhados na coleção. O Riva Fenix é desenvolvido em tecido soft drill, com efeito estonado. O solado foi trabalhado manualmente para acentuar o efeito chamuscado. A palmilha traz o carimbo da coleção.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '29858',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 3,
				'nome' => 'RIVA MOLETOM',
				'descricao' => 'Edição que levou para o Riva um dos tecidos clássicos da vestimenta de inverno. O moletom reveste todo o modelo deste tênis feminino, exceto pelo forro e palmilha de couro e o solado personalizado Osklen. Versões masculina e feminina.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '29789',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 4,
				'nome' => 'RIVA ENLUVADO',
				'descricao' => 'Versão clean do Riva. Essa edição Collection foi produzida em couro monocromático, com as costuras enluvadas (não aparentes) ressaltando a sofisticação do modelo. Versões masculina e feminina.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '29798',
				'fotos' => array(1, 2, 3, 4, 5, 6),
			),
			array(
				'exibir' => true,
				'id' => 5,
				'nome' => 'RIVA CETIM',
				'descricao' => 'O cetim, normalmente associado à produtos sofisticados, aparece no Riva reforçando o duo sofisticado e esportivo que o tênis simboliza. O modelo tem ponteiras de metal dourado personalizadas aplicadas nos cadarços.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '29799',
				'fotos' => array(1, 2),
			),
			array(
				'exibir' => true,
				'id' => 6,
				'nome' => 'RIVA ESPELHO',
				'descricao' => 'Inspirado no reflexo da luz no mar, o Riva collection desenvolvido para a coleção Oceans foi produzido em couro espelhado, efeito criado através da aplicação de filme metalizado no couro, combinando com os variados tons de azul trabalhados em toda a coleção.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '27584',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 7,
				'nome' => 'RIVA LONA COURO PEIXE',
				'descricao' => 'Primeiro Riva a receber detalhes em couro de peixe, fabric resultado da pesquisa realizada em parceria com o Instituto-e dentro do projeto e-fabrics. O modelo foi desenvolvido em lona de algodão e ganhou aplicação do couro especial nos tacos laterais. Versões masculina e feminina.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '27599',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 8,
				'nome' => 'RIVA LONA BICOLOR',
				'descricao' => 'O clássico preto e branco foi levado para o Riva que, pela primeira vez, apareceu com o solado personalizado na cor branca, combinando com o cabedal. Versões masculina e feminina.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '27615',
				'fotos' => array(1, 2, 3),
			),
			array(
				'exibir' => true,
				'id' => 9,
				'nome' => 'RIVA LONA LISA',
				'descricao' => 'Clássico, o Riva monocromático de lona de algodão é conhecido por suas cores vibrantes, estreando o trabalho colour também nos tênis. Foram criadas edições feminina e masculina e o modelo faz parte até hoje das coleções da Osklen.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '28060',
				'fotos' => array(1, 2, 3, 4, 5),
			),
		),
	),
	/* ANO fecha */
	/* ANO abre */
	array(
		'ano' => '2012',
		'modelos' => array(
			array(
				'exibir' => true,
				'id' => 1,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697-1518',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 2,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697-18126',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 3,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697-0524',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 4,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697-0507',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 5,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697-0512',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 6,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697-0748',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 7,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697-1330',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 8,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '12606-25101',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 9,
				'nome' => 'RIVA ONÇA',
				'descricao' => 'A partir do sucesso do Riva tigre, a Osklen lança a edição com estampa onça, alternando as cores e, mais uma vez, focando nos públicos feminino e masculino. O couro nobre com textura de pelos, utilizado normalmente em peças elaboradas, foi estampado através de técnica especial. ',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '27256',
				'fotos' => array(1, 2),
			),
			array(
				'exibir' => true,
				'id' => 10,
				'nome' => 'RIVA LONA ECO E COURO',
				'descricao' => 'A coleção Royal Black é marcada pela mistura dos tons natural, caramelo e preto, além de texturas naturais. Inspirado na coleção, o Riva foi desenvolvido em lona eco e-fabrics com detalhes de couro. Esse é também o primeiro Riva a não ter o trio de ilhóses esportivos, a fim de deixar o visual mais simples. O modelo ganhou versão com as costuras enluvadas (não aparentes), ressaltando o estilo clean da peça.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '31425',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 11,
				'nome' => 'RIVA LONA METALIZADA',
				'descricao' => 'Característico da coleção Royal Black, a cor Ouro foi muito utilizada para simbolizar a riqueza e sofisticação da cultura negra. Esse Riva foi desenvolvido em lona de algodão com efeito metalizado, ressaltando a elegância que existe também em materiais básico.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '31746',
				'fotos' => array(1, 2),
			),
			array(
				'exibir' => true,
				'id' => 12,
				'nome' => 'RIVA COURO PIQUET',
				'descricao' => 'Desenvolvido em napa de couro, esse Riva ganhou efeito piquet (micro furos) a partir da aplicação de prensa de metal quente na superfície do couro. O modelo foi desenvolvido nas versões masculina e feminina.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '32192',
				'fotos' => array(1, 2, 3),
			),
			array(
				'exibir' => true,
				'id' => 13,
				'nome' => 'RIVA ENLUVADO',
				'descricao' => 'Riva de couro também desenvolvido sem os ilhóses e com as costuras não aparentes, deixando o tênis com um visual mais clean. A partir desse modelo também começaram a ser trabalhados os cadarços de algodão encerado nas cores do couro. Versões feminina e masculina.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '32194',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 14,
				'nome' => 'RIVA VELVET',
				'descricao' => 'Tênis Riva Collection desenvolvido em veludo, continuando o trabalho de fusão entre o esportivo e o sofisticado, clássico da Osklen. O modelo é essencialmente feminino, com ponteiras de metal ouro aplicadas nos cadarços. ',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '32567',
				'fotos' => array(1, 2),
			),
			array(
				'exibir' => true,
				'id' => 15,
				'nome' => 'RIVA PSICODÉLICO',
				'descricao' => 'A estampa Psidcodélica marca a passarela da coleção A21 e aparece também no Riva, em lona de algodão. O modelo possui versões masculina e feminina e é caracterizado por suas cores marcantes.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '33574',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 16,
				'nome' => 'RIVA <span>CETIM ENLUVADO</span>',
				'descricao' => 'Mais uma vez o cetim aparece no Riva, dessa vez com detalhes em couro e costuras enluvadas (não aparentes). O modelo feminino traz as características clássicas do tênis, como o forro e palmilha 100% couro e o solado personalizado Osklen.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '33529',
				'fotos' => array(1, 2, 3, 4),
			),
			array(
				'exibir' => true,
				'id' => 17,
				'nome' => 'RIVA ROUGH',
				'descricao' => 'Tênis Riva Collection desenvolvido em couro. O modelo monocromático tem traços manchados naturais do couro resultado do trabalho artesanal feito no tênis após pronto. Por isso, um par nunca é igual ao outro. O modelo é um dos mais conhecidos e desejados, desenvolvido a cada temporada em novas cores.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '33568',
				'fotos' => array(1),
			),
		),
	),
	/* ANO fecha */
	/* ANO abre */
	array(
		'ano' => '2013',
		'modelos' => array(
			array(
				'exibir' => true,
				'id' => 1,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697-0382',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 2,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697-0330',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 3,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697-1412',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 4,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697-0727',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 5,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697-20336',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 6,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '12606-1856',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 7,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '12606-1836',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 8,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '12606-20338',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 9,
				'nome' => 'RIVA PELO MICROFURO',
				'descricao' => 'No clima da coleção Into the Mountains, o couro de pelo aparece vazado com laser, ganhando microfuros, mantendo ainda o aspecto esportivo, sofisticado e invernal. Modelo masculino.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '38014',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 10,
				'nome' => 'RIVA SPORT',
				'descricao' => 'Inspirados nos materiais dos clássicos tênis de performance, esse Riva mistura o nylon esportivo e a camurça de couro, ressaltando a versatilidade do modelo e reforçando a relação da Osklen com os esportes.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '38132',
				'fotos' => array(1, 2, 3, 4),
			),
			array(
				'exibir' => true,
				'id' => 11,
				'nome' => 'RIVA <span>CAMURÇA GRAXO</span>',
				'descricao' => 'O Riva de camurça de  couro ganha efeito graxo a partir do trabalho manual feito nele após pronto. O efeito foi concentrado principalmente no bico e calcanhar e torna cada par único.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '38167',
				'fotos' => array(1, 2, 3),
			),
			array(
				'exibir' => true,
				'id' => 12,
				'nome' => 'RIVA NERVURAS',
				'descricao' => 'Desde a coleção Rio de Janeiro, as nervuras transitam pelas coleções da Osklen e já são uma característica própria da marca. Nesse Riva, desenvolvido em napa de couro, o taco lateral é substituido pelas nervuras e traz os clássicos detalhes em couro.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '35632',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 13,
				'nome' => 'RIVA A TOPO',
				'descricao' => 'Na coleção Endless Summer, o Riva é colocado ao avesso. Desenvolvido em camurça de couro, o modelo Collection tem costura de topo, virada para fora, marcando os recortes do cabedal.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '33572',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 14,
				'nome' => 'RIVA BOLD',
				'descricao' => 'Inspirado no uniforme do exército brasileiro, o Riva Bold apresenta um couro mais robusto, característico dos coturnos militares. O modelo masculino se tornou sucesso e ganhou novas edições nas coleções seguintes.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '33850',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 15,
				'nome' => 'RIVA LINHO',
				'descricao' => 'Inspirado nas peças que marcam o visual praia, o Riva aparece tramado em linho. O modelo feminino e masculino tem as costuras embutidas a fim de deixar o visual ainda mais limpo e sofisticado.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '35585',
				'fotos' => array(1),
			),
		),
	),
	/* ANO fecha */
	/* ANO abre */
	array(
		'ano' => '2014',
		'modelos' => array(
			array(
				'exibir' => true,
				'id' => 1,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697-0227',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 2,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697-0227',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 3,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697-14141',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 4,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697-13131',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 5,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => '',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '12606-1412',
				'fotos' => array(1),
			),
			array(
				'exibir' => false,
				'id' => 6,
				'nome' => 'RIVA BLURRY GRANDSTAND',
				'descricao' => 'Estampa desenvolvida a partir de uma fotografia da torcida. A imagem foi alterada digitalmente para alcançar o efeito desejado e então surgiu o Riva Blurry Grandstand, parte da linha Collection.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '42124',
				'fotos' => array(),
			),
			array(
				'exibir' => false,
				'id' => 7,
				'nome' => 'RIVA <span>BLURRY GRANDSTAND</span>',
				'descricao' => 'Estampa desenvolvida a partir de uma fotografia da torcida. A imagem foi alterada digitalmente para alcançar o efeito desejado e então surgiu o Riva Blurry Grandstand, parte da linha Collection.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '42146',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 8,
				'nome' => 'RIVA MATELASSÊ',
				'descricao' => 'Desenvolvido em napa de couro, o Riva ganha efeito matelassê nos recortes do cabedal, inspirado nos uniformes dos goleiros. O material trabalhado é leve e macio a fim de tornar o matelassê mais evidente, como nas clássicas bolas de futebol.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '41249',
				'fotos' => array(1),
			),
			array(
				'exibir' => false,
				'id' => 9,
				'nome' => 'RIVA SOLA PB',
				'descricao' => 'A combinação de cores esportivas é o diferencial deste Riva de couro que tem a sola em preto e branco.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '42131',
				'fotos' => array(),
			),
			array(
				'exibir' => true,
				'id' => 10,
				'nome' => 'RIVA MESCLA',
				'descricao' => 'A malha mescla é conhecida por ser trabalhada em joggings e roupas esportivas e aparece nesse Riva que teve como inspiração o futebol e as referências clássicas do esporte.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '41251',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 11,
				'nome' => 'RIVA <span>COURO</span> COLOR',
				'descricao' => 'Tênis Riva nas versões masculina e feminina desenvolvido em couro, incluindo forro e palmilha. Solado personalizado Osklen.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '42136',
				'fotos' => array(1, 2),
			),
			array(
				'exibir' => false,
				'id' => 12,
				'nome' => 'RIVA <span>SPECIAL EDITION</span>',
				'descricao' => 'Tênis Riva Special Edition desenvolvido em lona de algodão para a coleção Football Series. Pela primeira vez, a faixa dupla do solado foi alterada para verde e amarelo. O modelo tem ainda carimbo personalizado na palmilha. Versões masculina e feminina.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '42125',
				'fotos' => array(),
			),
			array(
				'exibir' => true,
				'id' => 13,
				'nome' => 'RIVA SALMÃO',
				'descricao' => 'Pela primeira vez, o Riva foi desenvolvido em couro de salmão, dentro do projeto e-fabrics. O modelo feminino e masculino faz parte da linha Collection, e traz os detalhes clássicos em couro e o solado personalizado.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '42149',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 14,
				'nome' => 'RIVA <span>FOOTBALL SERIES</span>',
				'descricao' => 'Tênis Riva Special Edition desenvolvido em lona de algodão para a coleção Football Series, com faixa dupla do solado personalizada em verde e amarelo e carimbo personalizado aplicado na palmilha. Versões feminina e masculina.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '43641',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 15,
				'nome' => 'RIVA <span>TROPICAL STONES</span>',
				'descricao' => 'Parte da linha Collection, esse Riva desenvolvido em lona de algodão ganha a estampa Tropical Stones, emblemática da coleção 5521RIO e marcada por suas cores vibrantes e formas inspiradas nas gemas preciosas.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '39633',
				'fotos' => array(1),
			),
			array(
				'exibir' => true,
				'id' => 16,
				'nome' => 'RIVA VINTAGE',
				'descricao' => 'A inspiração para o Riva vintage vem dos antigos tênis utilizados por skatistas, depois de jea serem usados durante as manobras. Para alcançar o efeito desgastado, o modelo de couro ganha trabalho manual realizado após o tênis estar pronto.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '39645',
				'fotos' => array(1),
			),
		),
	),
	/* ANO fecha */
);
?>