<?php
$tenisArray = array(
	/* ANO abre */
	array(
		'ano' => '2006',
		'modelos' => array(
			array(
				'exibir' => true,
				'id' => 1,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => 'Primeiro modelo do Riva, desenhado em 2005 e lançado no inverno de 2006 pensado a princípio para o público masculino. O tênis foi desenvolvido tricolor e bicolor, com taco lateral e cabedal em tom diferente do restante do modelo. A peça foi desenvolvida em couro, incluindo forro e palmilha e o solado personalizado Osklen que, desde então, caracteriza nossas peças.',
				'link_compra' => 'http://store.osklen.com/catalogsearch/result/?q=11697',
				'link_compart' => 'http://store.osklen.com/tenis-riva-81502.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697',
				'fotos' => array('00_Riva_Classico_Masc1', '00_Riva_Classico_Masc2'),
			),
		),
	),
	/* ANO fecha */
	/* ANO abre */
	array(
		'ano' => '2007',
		'modelos' => array(
			array(
				'exibir' => true,
				'id' => 1,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => 'No verão 2007, a Osklen apresenta o Riva feminino, seguindo as mesmas características do modelo original, porém trabalhando cores e material mais atraentes para as mulheres. O primeiro Riva feminino foi desenvolvido em napa de couro, incluindo forro e palmilha.',
				'link_compra' => 'http://store.osklen.com/catalogsearch/result/?q=11697',
				'link_compart' => 'http://store.osklen.com/tenis-riva-81502.html',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '12606',
				'fotos' => array('00_Riva_ClassicoFem1','00_Riva_Classico_Masc1'),
			),
		),
	),
	/* ANO fecha */
	/* ANO abre  */
	array(
		'ano' => '2008',
		'modelos' => array(
			array(
				'exibir' => true,
				'id' => 1,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => 'Continuando seu lançamento de sucesso, em 2006, o Riva clássico ganha versão bicolor, em offwhite e marrom.  Essa foi apenas a primeira de inúmeras edições que o Riva viria a ganhar nos anos seguintes.',
				'link_compra' => 'http://store.osklen.com/catalogsearch/result/?q=11697',
				'link_compart' => 'http://store.osklen.com/tenis-riva-81502.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697',
				'fotos' => array('00_Riva_Classico_Masc1'),
			),
		),
	),
	/* ANO fecha */
	/* ANO abre */
	array(
		'ano' => '2009',
		'modelos' => array(
			array(
				'exibir' => true,
				'id' => 1,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => 'Dentro das inspirações para as temporadas verão e inverno desse ano, o Riva clássico, masculino e feminino ganham versões mais sóbrias, como o cinza, chumbo e o café, no inverno. No verão, a edição feminina trouxe frescor com tons como o rosa e menta combinados ao branco.',
				'link_compra' => 'http://store.osklen.com/catalogsearch/result/?q=11697',
				'link_compart' => 'http://store.osklen.com/tenis-riva-81502.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697/12606',
				'fotos' => array('00_Riva_Classico_Masc1','00_Riva_Classico_Masc2','00_Riva_Classico_Masc3','00_Riva_ClassicoFem1','00_Riva_ClassicoFem2'),
			),
		),
	),
	/* ANO fecha */
	/* ANO abre */
	array(
		'ano' => '2010',
		'modelos' => array(
			array(
				'exibir' => true,
				'id' => 1,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => 'O cinza, cor sempre presente nas coleções da Osklen, tem suas nuances trabalhadas nas versões lançadas esse ano, combinadas a diferentes tons de caramelo, além dos detalhes metalizados  oferecendo uma prévia do trabalho em couro metalizado lançado em seguida.',
				'link_compra' => 'http://store.osklen.com/catalogsearch/result/?q=11697',
				'link_compart' => 'http://store.osklen.com/tenis-riva-81502.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697/12606',
				'fotos' => array('00_Riva_Classico_Masc1','00_Riva_Classico_Masc2','00_Riva_Classico_Masc3','00_Riva_Classico_Masc4','00_Riva_Classico_Masc5','00_Riva_ClassicoFem1','00_Riva_ClassicoFem2'),
			),
			array(
				'exibir' => true,
				'id' => 2,
				'nome' => 'RIVA <span>NEW GOLD</span>',
				'descricao' => 'O couro metalizado ganha efeito craquelado, com aparência desgastada, nessa edição do Riva desenvolvida em versões masculina e feminina. O modelo é um dos mais conhecidos e aparece a cada temporada.',
				'link_compra' => 'http://store.osklen.com/tenis-riva-new-gold-fem.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-new-gold-fem.html',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '23822',
				'fotos' => array('01_Riva_NewGold'),
			),
			array(
				'exibir' => true,
				'id' => 3,
				'nome' => 'RIVA <span>BIG FLOATER</span>',
				'descricao' => 'Continuando o trabalho com o couro, o Riva feminino aparece monocromático, exceto pelo cabedal em tom caramelo,  e com texturas que formam pequenos relevos.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => false,
				'tipo' => 'F',
				'ref' => '23350',
				'fotos' => array('02_Riva_BigFloater'),
			),
			array(
				'exibir' => true,
				'id' => 4,
				'nome' => 'RIVA <span>LÃ</span>',
				'descricao' => 'Elementos sofisticados e esportivos se misturam na criação do primeiro Riva Collection, linha premium da Osklen. O modelo é  desenvolvido em lã, trama mais trabalhada em roupas, com detalhes em couro café.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => false,
				'tipo' => 'M',
				'ref' => '24882',
				'fotos' => array('04_Riva_La'),
			),
		),
	),
	/* ANO fecha */
	/* ANO abre */
	array(
		'ano' => '2011',
		'modelos' => array(
			array(
				'exibir' => true,
				'id' => 1,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => 'Dos oceanos ao fogo, as edições lançadas esse ano trazem combinações inéditas, como o caramelo com o preto, além da continuação dos detalhes em couro metalizado no Riva chumbo com cinza, remetendo ao incêndio que inspirou a coleção Fenix.',
				'link_compra' => 'http://store.osklen.com/catalogsearch/result/?q=11697',
				'link_compart' => 'http://store.osklen.com/tenis-riva-81502.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697/12606',
				'fotos' => array('00_Riva_Classico_Masc1','00_Riva_Classico_Masc2','00_Riva_Classico_Masc3','00_Riva_Classico_Masc4','00_Riva_ClassicoFem1'),
			),
			array(
				'exibir' => true,
				'id' => 2,
				'nome' => 'RIVA <span>FENIX</span>',
				'descricao' => 'A coleção tem como inspiração o incêndio sofrido pela sede da Osklen aquele ano. Das chamas e  objetos remanescentes surgiram estampas e ideias de materiais trabalhados na coleção. O Riva Fenix é desenvolvido em tecido soft drill, com efeito estonado. O solado foi trabalhado manualmente para acentuar o efeito chamuscado. A palmilha traz o carimbo da coleção.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => false,
				'tipo' => 'M',
				'ref' => '29858',
				'fotos' => array('01_Riva_Fenix'),
			),
			array(
				'exibir' => true,
				'id' => 3,
				'nome' => 'RIVA <span>MOLETOM</span>',
				'descricao' => 'Edição que levou para o Riva um dos tecidos clássicos da vestimenta de inverno. O moletom reveste todo o modelo deste tênis feminino, exceto pelo forro e palmilha de couro e o solado personalizado Osklen. Versões masculina e feminina.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => false,
				'tipo' => 'F',
				'ref' => '29789',
				'fotos' => array('02_Riva_Moletom'),
			),
			array(
				'exibir' => true,
				'id' => 4,
				'nome' => 'RIVA <span>ENLUVADO</span>',
				'descricao' => 'Versão clean do Riva. Essa edição Collection foi produzida em couro monocromático, com as costuras enluvadas (não aparentes) ressaltando a sofisticação do modelo. Versões masculina e feminina.',
				'link_compra' => 'http://store.osklen.com/tenis-riva-enluvado-masc-49851.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-enluvado-masc-49851.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '29798',
				'fotos' => array('03_Riva_Enluvado1','03_Riva_Enluvado2','03_Riva_Enluvado3','03_Riva_Enluvado4','03_Riva_Enluvado5','03_Riva_Enluvado6'),
			),
			array(
				'exibir' => true,
				'id' => 5,
				'nome' => 'RIVA <span>CETIM</span>',
				'descricao' => 'O cetim, normalmente associado à produtos sofisticados, aparece no Riva reforçando o duo sofisticado e esportivo que o tênis simboliza. O modelo tem ponteiras de metal dourado personalizadas aplicadas nos cadarços.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => false,
				'tipo' => 'F',
				'ref' => '29799',
				'fotos' => array('04_Riva_Cetim1','04_Riva_Cetim2'),
			),
			array(
				'exibir' => true,
				'id' => 6,
				'nome' => 'RIVA <span>TIGRE</span>',
				'descricao' => 'Mais uma vez o couro nobre foi trabalhado no tênis esportivo, mesclando a peça com a sofisticação da Osklen. Pela primeira vez, a estampa tigrada aparece aplicada no couro de pelos. O modelo foi desenvolvido em versões masculina e feminina quebrando o mito do animal print voltado apenas para as mulheres.',
				'link_compra' => 'http://store.osklen.com/catalog/product/view/id/12954',
				'link_compart' => 'http://store.osklen.com/catalog/product/view/id/12954',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '30146',
				'fotos' => array('05_Riva_Tigre'),
			),
			array(
				'exibir' => true,
				'id' => 7,
				'nome' => 'RIVA <span>ESPELHO</span>',
				'descricao' => 'Inspirado no reflexo da luz no mar, o Riva collection desenvolvido para a coleção Oceans foi produzido em couro espelhado, efeito criado através da aplicação de filme metalizado no couro, combinando com os variados tons de azul trabalhados em toda a coleção.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => false,
				'tipo' => 'F',
				'ref' => '27584',
				'fotos' => array('06_Riva_Espelho'),
			),
			array(
				'exibir' => true,
				'id' => 8,
				'nome' => 'RIVA <span>LONA COURO PEIXE</span>',
				'descricao' => 'Primeiro Riva a receber detalhes em couro de peixe, fabric resultado da pesquisa realizada em parceria com o Instituto-e dentro do projeto e-fabrics. O modelo foi desenvolvido em lona de algodão e ganhou aplicação do couro especial nos tacos laterais. Versões masculina e feminina.',
				'link_compra' => 'http://store.osklen.com/catalog/product/view/id/20428',
				'link_compart' => 'http://store.osklen.com/catalog/product/view/id/20428',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '27599',
				'fotos' => array('07_Riva_LonaCouroPeixe'),
			),
			array(
				'exibir' => true,
				'id' => 9,
				'nome' => 'RIVA <span>LONA BICOLOR</span>',
				'descricao' => 'O clássico preto e branco foi levado para o Riva que, pela primeira vez, apareceu com o solado personalizado na cor branca, combinando com o cabedal. Versões masculina e feminina.',
				'link_compra' => 'http://store.osklen.com/tenis-riva-lona-bicolor-48201.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-lona-bicolor-48201.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '27615',
				'fotos' => array('08_Riva_LonaBicolor1','08_Riva_LonaBicolor2','08_Riva_LonaBicolor3'),
			),
			array(
				'exibir' => true,
				'id' => 10,
				'nome' => 'RIVA <span>LONA LISA</span>',
				'descricao' => 'Clássico, o Riva monocromático de lona de algodão é conhecido por suas cores vibrantes, estreando o trabalho colour também nos tênis. Foram criadas edições feminina e masculina e o modelo faz parte até hoje das coleções da Osklen.',
				'link_compra' => 'http://store.osklen.com/tenis-riva-lona-lisa-masc-52920.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-lona-lisa-masc-52920.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '28060',
				'fotos' => array('08_Riva_LonaLisa1','08_Riva_LonaLisa2','08_Riva_LonaLisa3','08_Riva_LonaLisa4','08_Riva_LonaLisa5'),
			),
		),
	),
	/* ANO fecha */
	/* ANO abre */
	array(
		'ano' => '2012',
		'modelos' => array(
			array(
				'exibir' => true,
				'id' => 1,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => 'Mais sofisticadas, em 2012 as edições lançadas apresentam contrastes suaves e elegantes, levando para o Riva as inspirações de Royal Black e A21, ambas coleções mais orgânicas.',
				'link_compra' => 'http://store.osklen.com/catalogsearch/result/?q=11697',
				'link_compart' => 'http://store.osklen.com/tenis-riva-81502.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697/12606',
				'fotos' => array('00_Riva_Classico_Masc1','00_Riva_Classico_Masc2','00_Riva_Classico_Masc3','00_Riva_Classico_Masc4','00_Riva_Classico_Masc5','00_Riva_Classico_Masc6','00_Riva_ClassicoFem1','00_Riva_ClassicoFem2','00_Riva_ClassicoFem3'),
			),
			array(
				'exibir' => true,
				'id' => 2,
				'nome' => 'RIVA <span>ONÇA</span>',
				'descricao' => 'A partir do sucesso do Riva tigre, a Osklen lança a edição com estampa onça, alternando as cores e, mais uma vez, focando nos públicos feminino e masculino. O couro nobre com textura de pelos, utilizado normalmente em peças elaboradas, foi estampado através de técnica especial. ',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => false,
				'tipo' => 'F',
				'ref' => '27256',
				'fotos' => array('01_Riva_Oncinha_1','01_Riva_Oncinha_2'),
			),
			array(
				'exibir' => true,
				'id' => 3,
				'nome' => 'RIVA <span>LONA ECO E COURO</span>',
				'descricao' => 'A coleção Royal Black é marcada pela mistura dos tons natural, caramelo e preto, além de texturas naturais. Inspirado na coleção, o Riva foi desenvolvido em lona eco e-fabrics com detalhes de couro. Esse é também o primeiro Riva a não ter o trio de ilhóses esportivos, a fim de deixar o visual mais simples. O modelo ganhou versão com as costuras enluvadas (não aparentes), ressaltando o estilo clean da peça.',
				'link_compra' => 'http://store.osklen.com/catalog/product/view/id/25748',
				'link_compart' => 'http://store.osklen.com/catalog/product/view/id/25748',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '31425',
				'fotos' => array('02_Riva_Eco_eCouro'),
			),
			array(
				'exibir' => true,
				'id' => 4,
				'nome' => 'RIVA <span>LONA METALIZADA</span>',
				'descricao' => 'Característico da coleção Royal Black, a cor Ouro foi muito utilizada para simbolizar a riqueza e sofisticação da cultura negra. Esse Riva foi desenvolvido em lona de algodão com efeito metalizado, ressaltando a elegância que existe também em materiais básico.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => false,
				'tipo' => 'F',
				'ref' => '31746',
				'fotos' => array('03_Riva_Lona_Metalizada1','03_Riva_Lona_Metalizada2'),
			),
			array(
				'exibir' => true,
				'id' => 5,
				'nome' => 'RIVA <span>COURO PIQUET</span>',
				'descricao' => 'Desenvolvido em napa de couro, esse Riva ganhou efeito piquet (micro furos) a partir da aplicação de prensa de metal quente na superfície do couro. O modelo foi desenvolvido nas versões masculina e feminina.',
				'link_compra' => 'http://store.osklen.com/tenis-riva-couro-piquet-masc-48149.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-couro-piquet-masc-48149.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '32192',
				'fotos' => array('04_Riva_Couro_Piquet1','04_Riva_Couro_Piquet2','04_Riva_Couro_Piquet3'),
			),
			array(
				'exibir' => true,
				'id' => 6,
				'nome' => 'RIVA <span>ENLUVADO</span>',
				'descricao' => 'Riva de couro também desenvolvido sem os ilhóses e com as costuras não aparentes, deixando o tênis com um visual mais clean. A partir desse modelo também começaram a ser trabalhados os cadarços de algodão encerado nas cores do couro. Versões feminina e masculina.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => false,
				'tipo' => 'M',
				'ref' => '32194',
				'fotos' => array('05_Riva_Enluvado'),
			),
			array(
				'exibir' => true,
				'id' => 7,
				'nome' => 'RIVA <span>VELVET</span>',
				'descricao' => 'Tênis Riva Collection desenvolvido em veludo, continuando o trabalho de fusão entre o esportivo e o sofisticado, clássico da Osklen. O modelo é essencialmente feminino, com ponteiras de metal ouro aplicadas nos cadarços. ',
				'link_compra' => 'http://store.osklen.com/tenis-riva-velvet-fem.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-velvet-fem.html',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '32567',
				'fotos' => array('06_Riva_Velvet1','06_Riva_Velvet2'),
			),
			array(
				'exibir' => true,
				'id' => 8,
				'nome' => 'RIVA <span>PSICODÉLICO</span>',
				'descricao' => 'A estampa Psidcodélica marca a passarela da coleção A21 e aparece também no Riva, em lona de algodão. O modelo possui versões masculina e feminina e é caracterizado por suas cores marcantes.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => false,
				'tipo' => 'F',
				'ref' => '33574',
				'fotos' => array('07_Riva_Psicodelico'),
			),
			array(
				'exibir' => true,
				'id' => 9,
				'nome' => 'RIVA <span>CETIM ENLUVADO</span>',
				'descricao' => 'Mais uma vez o cetim aparece no Riva, dessa vez com detalhes em couro e costuras enluvadas (não aparentes). O modelo feminino traz as características clássicas do tênis, como o forro e palmilha 100% couro e o solado personalizado Osklen.',
				'link_compra' => 'http://store.osklen.com/tenis-riva-cetim-enluvado-fem-55939.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-cetim-enluvado-fem-55939.html',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '33529',
				'fotos' => array('08_Riva_Cetim_Enluvado1','08_Riva_Cetim_Enluvado2','08_Riva_Cetim_Enluvado3','08_Riva_Cetim_Enluvado4'),
			),
			array(
				'exibir' => true,
				'id' => 10,
				'nome' => 'RIVA <span>ROUGH</span>',
				'descricao' => 'Tênis Riva Collection desenvolvido em couro. O modelo monocromático tem traços manchados naturais do couro resultado do trabalho artesanal feito no tênis após pronto. Por isso, um par nunca é igual ao outro. O modelo é um dos mais conhecidos e desejados, desenvolvido a cada temporada em novas cores.',
				'link_compra' => 'http://store.osklen.com/tenis-riva-rough-masc.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-rough-masc.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '33568',
				'fotos' => array('09_Riva_Rough'),
			),
		),
	),
	/* ANO fecha */
	/* ANO abre */
	array(
		'ano' => '2013',
		'modelos' => array(
			array(
				'exibir' => true,
				'id' => 1,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => 'A sofisticação e o esporte se reunem nesse clássico lançado em 2013 em cores vivas, incluindo combinações mais contrastantes, como o verde, cinza e azul e o preto, laranja e caramelo. Outras versões apresentam os detalhes em couro metalizado apresentado anos antes e consagrados na trajetória do Riva.',
				'link_compra' => 'http://store.osklen.com/catalogsearch/result/?q=11697',
				'link_compart' => 'http://store.osklen.com/tenis-riva-81502.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697/12606',
				'fotos' => array('00_Riva_Classico_Masc1','00_Riva_Classico_Masc2','00_Riva_Classico_Masc3','00_Riva_Classico_Masc4','00_Riva_Classico_Masc5','00_Riva_ClassicoFem1','00_Riva_ClassicoFem2','00_Riva_ClassicoFem3','00_Riva_ClassicoFem4'),
			),
			array(
				'exibir' => true,
				'id' => 2,
				'nome' => 'RIVA <span>PELO MICROFURO</span>',
				'descricao' => 'No clima da coleção Into the Mountains, o couro de pelo aparece vazado com laser, ganhando microfuros, mantendo ainda o aspecto esportivo, sofisticado e invernal. Modelo masculino.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => false,
				'tipo' => 'M',
				'ref' => '38014',
				'fotos' => array('01_Riva_Microfuros'),
			),
			array(
				'exibir' => true,
				'id' => 3,
				'nome' => 'RIVA <span>SPORT</span>',
				'descricao' => 'Inspirados nos materiais dos clássicos tênis de performance, esse Riva mistura o nylon esportivo e a camurça de couro, ressaltando a versatilidade do modelo e reforçando a relação da Osklen com os esportes.',
				'link_compra' => 'http://store.osklen.com/tenis-riva-sport-masc-34012.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-sport-masc-34012.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '38132',
				'fotos' => array('02_Riva_Sport_1','02_Riva_Sport_2','02_Riva_Sport_3','02_Riva_Sport_4'),
			),
			array(
				'exibir' => true,
				'id' => 4,
				'nome' => 'RIVA <span>CAMURÇA GRAXO</span>',
				'descricao' => 'O Riva de camurça de  couro ganha efeito graxo a partir do trabalho manual feito nele após pronto. O efeito foi concentrado principalmente no bico e calcanhar e torna cada par único.',
				'link_compra' => 'http://store.osklen.com/tenis-riva-camurca-graxo-masc.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-camurca-graxo-masc.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '38167',
				'fotos' => array('03_Riva_CamurcaGraxo_1','03_Riva_CamurcaGraxo_2','03_Riva_CamurcaGraxo_3'),
			),
			array(
				'exibir' => true,
				'id' => 5,
				'nome' => 'RIVA <span>NERVURAS</span>',
				'descricao' => 'Desde a coleção Rio de Janeiro, as nervuras transitam pelas coleções da Osklen e já são uma característica própria da marca. Nesse Riva, desenvolvido em napa de couro, o taco lateral é substituido pelas nervuras e traz os clássicos detalhes em couro.',
				'link_compra' => 'http://store.osklen.com/tenis-arpoador-soft-wrinkled-masc-51929.html',
				'link_compart' => 'http://store.osklen.com/tenis-arpoador-soft-wrinkled-masc-51929.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '35632',
				'fotos' => array('04_Riva_Nervuras'),
			),
			array(
				'exibir' => true,
				'id' => 6,
				'nome' => 'RIVA <span>A TOPO</span>',
				'descricao' => 'Na coleção Endless Summer, o Riva é colocado ao avesso. Desenvolvido em camurça de couro, o modelo Collection tem costura de topo, virada para fora, marcando os recortes do cabedal.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => false,
				'tipo' => 'M',
				'ref' => '33572',
				'fotos' => array('05_Riva_A_Topo'),
			),
			array(
				'exibir' => true,
				'id' => 7,
				'nome' => 'RIVA <span>BOLD</span>',
				'descricao' => 'Inspirado no uniforme do exército brasileiro, o Riva Bold apresenta um couro mais robusto, característico dos coturnos militares. O modelo masculino se tornou sucesso e ganhou novas edições nas coleções seguintes.',
				'link_compra' => 'http://store.osklen.com/tenis-riva-bold-masc.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-bold-masc.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '33850',
				'fotos' => array('07_Riva_Bold'),
			),
			array(
				'exibir' => true,
				'id' => 8,
				'nome' => 'RIVA <span>LINHO</span>',
				'descricao' => 'Inspirado nas peças que marcam o visual praia, o Riva aparece tramado em linho. O modelo feminino e masculino tem as costuras embutidas a fim de deixar o visual ainda mais limpo e sofisticado.',
				'link_compra' => 'http://store.osklen.com/tenis-riva-linho.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-linho.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '35585',
				'fotos' => array('08_Riva_Linho'),
			),
		),
	),
	/* ANO fecha */
	/* ANO abre */
	array(
		'ano' => '2014',
		'modelos' => array(
			array(
				'exibir' => true,
				'id' => 1,
				'nome' => 'RIVA CLÁSSICO',
				'descricao' => 'O trabalho colour, iniciado nas peças Osklen, chega ao Riva resultando em edições vibrantes desse clássico. As cores vivas são sofisticadas pelas combinações com tons neutros, branco e o preto.  Em outro momento, é lançado também edição especial, nas cores, verde, amarelo e branco, em homenagem ao futebol, inspiração da coleção de inverno desse ano.',
				'link_compra' => 'http://store.osklen.com/catalogsearch/result/?q=11697',
				'link_compart' => 'http://store.osklen.com/tenis-riva-81502.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '11697/12606',
				'fotos' => array('00_Riva_Classico_masc1','00_Riva_Classico_masc2','00_Riva_Classico_masc3','00_Riva_Classico_masc4'),
			),
			array(
				'exibir' => false,
				'id' => 2,
				'nome' => 'RIVA <span>BLURRY GRANDSTAND</span>',
				'descricao' => 'Estampa desenvolvida a partir de uma fotografia da torcida. A imagem foi alterada digitalmente para alcançar o efeito desejado e então surgiu o Riva Blurry Grandstand, parte da linha Collection.',
				'link_compra' => 'http://store.osklen.com/catalog/product/view/id/48958',
				'link_compart' => 'http://store.osklen.com/catalog/product/view/id/48958',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '42124/42146',
				'fotos' => array('01_Riva_Grandstand_fem'),
			),
			array(
				'exibir' => true,
				'id' => 3,
				'nome' => 'RIVA <span>MATELASSÊ</span>',
				'descricao' => 'Desenvolvido em napa de couro, o Riva ganha efeito matelassê nos recortes do cabedal, inspirado nos uniformes dos goleiros. O material trabalhado é leve e macio a fim de tornar o matelassê mais evidente, como nas clássicas bolas de futebol.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => false,
				'tipo' => 'F',
				'ref' => '41249',
				'fotos' => array('02_Riva_Matelasse'),
			),
			array(
				'exibir' => true,
				'id' => 4,
				'nome' => 'RIVA <span>MESCLA</span>',
				'descricao' => 'A malha mescla é conhecida por ser trabalhada em joggings e roupas esportivas e aparece nesse Riva que teve como inspiração o futebol e as referências clássicas do esporte.',
				'link_compra' => 'http://store.osklen.com/catalog/product/view/id/47837',
				'link_compart' => 'http://store.osklen.com/catalog/product/view/id/47837',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '41251',
				'fotos' => array('04_Riva_Mescla'),
			),
			array(
				'exibir' => true,
				'id' => 5,
				'nome' => 'RIVA <span>COURO</span> COLOR',
				'descricao' => 'Tênis Riva nas versões masculina e feminina desenvolvido em couro, incluindo forro e palmilha. Solado personalizado Osklen.',
				'link_compra' => 'http://store.osklen.com/tenis-riva-couro-colour-fem-52876.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-couro-colour-fem-52876.html',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '42136',
				'fotos' => array('05_Riva_courocolor_fem1','05_Riva_courocolor_fem2'),
			),
			array(
				'exibir' => false,
				'id' => 6,
				'nome' => 'RIVA <span>SPECIAL EDITION</span>',
				'descricao' => 'Tênis Riva Special Edition desenvolvido em lona de algodão para a coleção Football Series. Pela primeira vez, a faixa dupla do solado foi alterada para verde e amarelo. O modelo tem ainda carimbo personalizado na palmilha. Versões masculina e feminina.',
				'link_compra' => 'http://store.osklen.com/tenis-riva-special-edition-masc.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-special-edition-masc.html',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '42125',
				'fotos' => array('06_Riva_SpecialEdition'),
			),
			array(
				'exibir' => true,
				'id' => 7,
				'nome' => 'RIVA <span>SALMÃO</span>',
				'descricao' => 'Pela primeira vez, o Riva foi desenvolvido em couro de salmão, dentro do projeto e-fabrics. O modelo feminino e masculino faz parte da linha Collection, e traz os detalhes clássicos em couro e o solado personalizado.',
				'link_compra' => '',
				'link_compart' => '',
				'disponivel' => false,
				'tipo' => 'M',
				'ref' => '42149',
				'fotos' => array('07_Riva_Salmao'),
			),
			array(
				'exibir' => true,
				'id' => 8,
				'nome' => 'RIVA <span>FOOTBALL SERIES</span>',
				'descricao' => 'Tênis Riva Special Edition desenvolvido em lona de algodão para a coleção Football Series, com solado verde e faixa dupla personalizada em amarelo e branco e carimbo personalizado aplicado na palmilha. Versões feminina e masculina.',
				'link_compra' => 'http://store.osklen.com/tenis-riva-futebol-series-fem.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-futebol-series-fem.html',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '43641',
				'fotos' => array('08_Riva_FootballSeries_fem'),
			),
			array(
				'exibir' => true,
				'id' => 9,
				'nome' => 'RIVA <span>TROPICAL STONES</span>',
				'descricao' => 'Parte da linha Collection, esse Riva desenvolvido em lona de algodão ganha a estampa Tropical Stones, emblemática da coleção 5521RIO e marcada por suas cores vibrantes e formas inspiradas nas gemas preciosas.',
				'link_compra' => 'http://store.osklen.com/catalog/product/view/id/40946',
				'link_compart' => 'http://store.osklen.com/catalog/product/view/id/40946',
				'disponivel' => true,
				'tipo' => 'F',
				'ref' => '39633',
				'fotos' => array('09_Riva_TropicalStones'),
			),
			array(
				'exibir' => true,
				'id' => 10,
				'nome' => 'RIVA <span>VINTAGE</span>',
				'descricao' => 'A inspiração para o Riva vintage vem dos antigos tênis utilizados por skatistas, depois de jea serem usados durante as manobras. Para alcançar o efeito desgastado, o modelo de couro ganha trabalho manual realizado após o tênis estar pronto.',
				'link_compra' => 'http://store.osklen.com/tenis-riva-vintage-masc.html',
				'link_compart' => 'http://store.osklen.com/tenis-riva-vintage-masc.html',
				'disponivel' => true,
				'tipo' => 'M',
				'ref' => '39645',
				'fotos' => array('10_Riva_Vintage'),
			),
		),
	),
	/* ANO fecha */
);
?>