<?php 


$titulo = "LB WOMEN  S|S 14";
$titulo_en = $titulo;

$galeriapasta = "lookbook_fem_2e_pt";
$largurathumb = "180";
$setinhas = "true";

$galeria = array(
		'LB_fem_inhotim_ipad.jpg',
		'LB_fem_inhotim_ipad2.jpg',
		'LB_fem_inhotim_ipad3.jpg',
		'LB_fem_inhotim_ipad4.jpg',
		'LB_fem_inhotim_ipad5.jpg',
		'LB_fem_inhotim_ipad6.jpg',
		'LB_fem_inhotim_ipad7.jpg',
		'LB_fem_inhotim_ipad8.jpg',
		'LB_fem_inhotim_ipad9.jpg',
		'LB_fem_inhotim_ipad10.jpg',
		'LB_fem_inhotim_ipad11.jpg',
		'LB_fem_inhotim_ipad12.jpg',
		'LB_fem_inhotim_ipad13.jpg',
		'LB_fem_inhotim_ipad14.jpg',
		'LB_fem_inhotim_ipad15.jpg',
		'LB_fem_inhotim_ipad16.jpg',
		'LB_fem_inhotim_ipad17.jpg',
		'LB_fem_inhotim_ipad18.jpg',
		'LB_fem_inhotim_ipad19.jpg',
		'LB_fem_inhotim_ipad20.jpg',
		'LB_fem_inhotim_ipad21.jpg',
		'LB_fem_inhotim_ipad22.jpg',
		'LB_fem_inhotim_ipad23.jpg',
		'LB_fem_inhotim_ipad24.jpg',
		'LB_fem_inhotim_ipad25.jpg',
		'LB_fem_inhotim_ipad26.jpg',
		'LB_fem_inhotim_ipad27.jpg',
		'LB_fem_inhotim_ipad28.jpg',
		'LB_fem_inhotim_ipad29.jpg',
		'LB_fem_inhotim_ipad30.jpg',
		'LB_fem_inhotim_ipad31.jpg',
		'LB_fem_inhotim_ipad32.jpg',
		'LB_fem_inhotim_ipad33.jpg',
		'LB_fem_inhotim_ipad34.jpg',
		'LB_fem_inhotim_ipad35.jpg',
		'LB_fem_inhotim_ipad36.jpg',
		'LB_fem_inhotim_ipad37.jpg',
		'LB_fem_inhotim_ipad38.jpg',
		'LB_fem_inhotim_ipad39.jpg',
		'LB_fem_inhotim_ipad40.jpg',
		'LB_fem_inhotim_ipad41.jpg',
		'LB_fem_inhotim_ipad42.jpg',
		'LB_fem_inhotim_ipad43.jpg',
		'LB_fem_inhotim_ipad44.jpg',
		'LB_fem_inhotim_ipad45.jpg',
		'LB_fem_inhotim_ipad46.jpg',
		'LB_fem_inhotim_ipad47.jpg',
		'LB_fem_inhotim_ipad48.jpg',
		'LB_fem_inhotim_ipad49.jpg',
		'LB_fem_inhotim_ipad50.jpg',
		'LB_fem_inhotim_ipad51.jpg',
		'LB_fem_inhotim_ipad52.jpg',
		'LB_fem_inhotim_ipad53.jpg',
		'LB_fem_inhotim_ipad54.jpg',
		'LB_fem_inhotim_ipad55.jpg',
		'LB_fem_inhotim_ipad56.jpg',
		'LB_fem_inhotim_ipad57.jpg',
		'LB_fem_inhotim_ipad58.jpg',
		'LB_fem_inhotim_ipad59.jpg',
		'LB_fem_inhotim_ipad60.jpg',
		'LB_fem_inhotim_ipad61.jpg',
		'LB_fem_inhotim_ipad62.jpg',
		'LB_fem_inhotim_ipad63.jpg',
		'LB_fem_inhotim_ipad64.jpg',
		'LB_fem_inhotim_ipad65.jpg',
		'LB_fem_inhotim_ipad66.jpg',
		'LB_fem_inhotim_ipad67.jpg',
		'LB_fem_inhotim_ipad68.jpg',
		'LB_fem_inhotim_ipad69.jpg',
		'lookbook_fem_01.jpg',
		'lookbook_fem_02.jpg',
		'lookbook_fem_03.jpg',
		'lookbook_fem_04.jpg',
		'lookbook_fem_05.jpg',
		'lookbook_fem_06.jpg',
		'lookbook_fem_07.jpg',
		'lookbook_fem_08.jpg',
		'lookbook_fem_09.jpg',
		'lookbook_fem_10.jpg',
		'lookbook_fem_11.jpg',
		'lookbook_fem_12.jpg',
		'lookbook_fem_13.jpg',
		'lookbook_fem_14.jpg',
		'lookbook_fem_15.jpg',
		'lookbook_fem_16.jpg',
		'lookbook_fem_17.jpg',
		'lookbook_fem_18.jpg',
		'lookbook_fem_19.jpg',
		'lookbook_fem_20.jpg',
		'lookbook_fem_21.jpg',
		'lookbook_fem_22.jpg',
		'lookbook_fem_23.jpg',
		'lookbook_fem_24.jpg',
		'lookbook_fem_25.jpg',
		'lookbook_fem_26.jpg',
		'lookbook_fem_27.jpg',
		'lookbook_fem_28.jpg',
		'lookbook_fem_29.jpg',
		'lookbook_fem_30.jpg',
		'lookbook_fem_31.jpg',
		'lookbook_fem_32.jpg',
		'lookbook_fem_33.jpg',
		'lookbook_fem_34.jpg',
		'lookbook_fem_35.jpg',
		'lookbook_fem_36.jpg',
		'lookbook_fem_37.jpg'

		);


?>