<?php 


$titulo = "CLIPPING";
$titulo_en = $titulo;

$galeriapasta = "clipping";
$largurathumb = "247";
$setinhas = "true";

$galeria = array(
		'Presskit_Internacional-site_high_ing-3.jpg',
		'Presskit_Internacional-site_high_ing-4.jpg',
		'Presskit_Internacional-site_high_ing-5.jpg',
		'Presskit_Internacional-site_high_ing-6.jpg',
		'Presskit_Internacional-site_high_ing-7.jpg',
		'Presskit_Internacional-site_high_ing-8.jpg',
		'Presskit_Internacional-site_high_ing-9.jpg',
		'Presskit_Internacional-site_high_ing-10.jpg',
		'Presskit_Internacional-site_high_ing-11.jpg',
		'Presskit_Internacional-site_high_ing-12.jpg',
		'Presskit_Internacional-site_high_ing-13.jpg',
		'Presskit_Internacional-site_high_ing-14.jpg',
		'Presskit_Internacional-site_high_ing-15.jpg',
		'Presskit_Internacional-site_high_ing-16.jpg',
		'Presskit_Internacional-site_high_ing-17.jpg',
		'Presskit_Internacional-site_high_ing-18.jpg',
		'Presskit_Internacional-site_high_ing-19.jpg',
		'Presskit_Internacional-site_high_ing-20.jpg',
		'Presskit_Internacional-site_high_ing-21.jpg',
		'Presskit_Internacional-site_high_ing-22.jpg',
		'Presskit_Internacional-site_high_ing-23.jpg',
		'Presskit_Internacional-site_high_ing-24.jpg',
		'Presskit_Internacional-site_high_ing-25.jpg',
		'Presskit_Internacional-site_high_ing-26.jpg',
		'Presskit_Internacional-site_high_ing-27.jpg',
		'Presskit_Internacional-site_high_ing-28.jpg',
		'Presskit_Internacional-site_high_ing-29.jpg',
		'Presskit_Internacional-site_high_ing-30.jpg',
		'Presskit_Internacional-site_high_ing-31.jpg',
		'Presskit_Internacional-site_high_ing-32.jpg',
		'Presskit_Internacional-site_high_ing-33.jpg',
		'Presskit_Internacional-site_high_ing-34.jpg',
		'Presskit_Internacional-site_high_ing-35.jpg',
		'Presskit_Internacional-site_high_ing-36.jpg',
		'Presskit_Internacional-site_high_ing-37.jpg',
		'Presskit_Internacional-site_high_ing-38.jpg',
		'Presskit_Internacional-site_high_ing-39.jpg',
		'Presskit_Internacional-site_high_ing-40.jpg',
		'Presskit_Internacional-site_high_ing-41.jpg',
		'Presskit_Internacional-site_high_ing-42.jpg',
		'Presskit_Internacional-site_high_ing-43.jpg',
		'Presskit_Internacional-site_high_ing-44.jpg',
		'Presskit_Internacional-site_high_ing-45.jpg',
		'Presskit_Internacional-site_high_ing-46.jpg',
		'Presskit_Internacional-site_high_ing-47.jpg',
		'Presskit_Internacional-site_high_ing-48.jpg',
		'Presskit_Internacional-site_high_ing-49.jpg',
		'Presskit_Internacional-site_high_ing-50.jpg',
		'Presskit_Internacional-site_high_ing-51.jpg',
		'Presskit_Internacional-site_high_ing-52.jpg',
		'Presskit_Internacional-site_high_ing-53.jpg',
		'Presskit_Internacional-site_high_ing-54.jpg',
		'Presskit_Internacional-site_high_ing-55.jpg',
		'Presskit_Internacional-site_high_ing-56.jpg',
		'Presskit_Internacional-site_high_ing-57.jpg',
		'Presskit_Internacional-site_high_ing-58.jpg',
		'Presskit_Internacional-site_high_ing-59.jpg',
		'Presskit_Internacional-site_high_ing-60.jpg',
		'Presskit_Internacional-site_high_ing-61.jpg',
		'Presskit_Internacional-site_high_ing-62.jpg',
		'Presskit_Internacional-site_high_ing-63.jpg',
		'Presskit_Internacional-site_high_ing-64.jpg',
		'Presskit_Internacional-site_high_ing-65.jpg',
		'Presskit_Internacional-site_high_ing-66.jpg',
		'Presskit_Internacional-site_high_ing-67.jpg',
		'Presskit_Internacional-site_high_ing-68.jpg',
		'Presskit_Internacional-site_high_ing-69.jpg',
		'Presskit_Internacional-site_high_ing-70.jpg',
		'Presskit_Internacional-site_high_ing-71.jpg',
		'Presskit_Internacional-site_high_ing-72.jpg',
		'Presskit_Internacional-site_high_ing-73.jpg',
		'Presskit_Internacional-site_high_ing-74.jpg',
		'Presskit_Internacional-site_high_ing-75.jpg',
		'Presskit_Internacional-site_high_ing-76.jpg',
		'Presskit_Internacional-site_high_ing-77.jpg',
		'Presskit_Internacional-site_high_ing-78.jpg',
		'Presskit_Internacional-site_high_ing-79.jpg',
		'Presskit_Internacional-site_high_ing-80.jpg',
		'Presskit_Internacional-site_high_ing-81.jpg',
		'Presskit_Internacional-site_high_ing-82.jpg',
		'Presskit_Internacional-site_high_ing-83.jpg',
		'Presskit_Internacional-site_high_ing-84.jpg',
		'Presskit_Internacional-site_high_ing-85.jpg',
		'Presskit_Internacional-site_high_ing-86.jpg',
		'Presskit_Internacional-site_high_ing-87.jpg',
		'Presskit_Internacional-site_high_ing-88.jpg'

		);


?>